In [2]:
import pandas as pd

In [6]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [7]:
!wget https://raw.githubusercontent.com/sagnikghoshcr7/Bank-Customer-Churn-Prediction/master/Churn_Modelling.csv

--2024-03-08 09:49:30--  https://raw.githubusercontent.com/sagnikghoshcr7/Bank-Customer-Churn-Prediction/master/Churn_Modelling.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 684856 (669K) [text/plain]
Saving to: ‘Churn_Modelling.csv’

Churn_Modelling.csv 100%[===================>] 668.80K  --.-KB/s    in 0.03s

2024-03-08 09:49:30 (19.3 MB/s) - ‘Churn_Modelling.csv’ saved [684856/684856]

In [8]:
df = pd.read_csv("Churn_Modelling.csv")

In [9]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [11]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], inplace=True, axis=1)

In [12]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:
df["Geography"].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [15]:
df["Gender"].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [17]:
df=pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True)

In [18]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [20]:
X=df.drop(["Exited"], axis=1)

In [21]:
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0

In [22]:
y=df["Exited"]

In [23]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [25]:
import tensorflow
from tensorflow import keras

In [27]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [28]:
len(X.columns)

11

In [34]:
model=Sequential()
model.add(Dense(11,activation="sigmoid", input_dim=11)) # input layer
model.add(Dense(11,activation="sigmoid")) # hidden layer
model.add(Dense(1,activation="sigmoid")) # output layer

In [36]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 11)                132

 dense_10 (Dense)            (None, 11)                132

 dense_11 (Dense)            (None, 1)                 12

=================================================================
Total params: 276 (1.08 KB)
Trainable params: 276 (1.08 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

In [40]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [43]:
X_train_tf=scaler.fit_transform(X_train)
X_test_tf=scaler.transform(X_test)

In [46]:
model.compile(optimizer="Adam", loss="binary_crossentropy", metrics=["accuracy"])

In [49]:
model.fit(X_train_tf, y_train, epochs=50, verbose=1)

Epoch 1/50
250/250 [==============================] - 2s 5ms/step - loss: 0.4733 - accuracy: 0.7960
Epoch 2/50
250/250 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.8021
Epoch 3/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4300 - accuracy: 0.8142
Epoch 4/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4250 - accuracy: 0.8148
Epoch 5/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4215 - accuracy: 0.8181
Epoch 6/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4185 - accuracy: 0.8238
Epoch 7/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4157 - accuracy: 0.8239
Epoch 8/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4133 - accuracy: 0.8271
Epoch 9/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4107 - accuracy: 0.8292
Epoch 10/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4081 - accuracy: 0.8329
Epoch 11/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4056 - accuracy: 0.8347
Epoch 12/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4030 - accuracy: 0.8353
Epoch 13/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4006 - accuracy: 0.8361
Epoch 14/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3977 - accuracy: 0.8363
Epoch 15/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3955 - accuracy: 0.8394
Epoch 16/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3929 - accuracy: 0.8391
Epoch 17/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3903 - accuracy: 0.8394
Epoch 18/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3877 - accuracy: 0.8415
Epoch 19/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3849 - accuracy: 0.8405
Epoch 20/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3824 - accuracy: 0.8431
Epoch 21/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3797 - accuracy: 0.8445
Epoch 22/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3771 - accuracy: 0.8460
Epoch 23/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3747 - accuracy: 0.8481
Epoch 24/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3723 - accuracy: 0.8505
Epoch 25/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3698 - accuracy: 0.8493
Epoch 26/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3674 - accuracy: 0.8491
Epoch 27/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3655 - accuracy: 0.8529
Epoch 28/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3631 - accuracy: 0.8546
Epoch 29/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3607 - accuracy: 0.8555
Epoch 30/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3593 - accuracy: 0.8554
Epoch 31/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3573 - accuracy: 0.8565
Epoch 32/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3556 - accuracy: 0.8581
Epoch 33/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3540 - accuracy: 0.8584
Epoch 34/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3527 - accuracy: 0.8604
Epoch 35/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3511 - accuracy: 0.8590
Epoch 36/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3502 - accuracy: 0.8602
Epoch 37/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3486 - accuracy: 0.8599
Epoch 38/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3473 - accuracy: 0.8605
Epoch 39/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3465 - accuracy: 0.8589
Epoch 40/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3455 - accuracy: 0.8615
Epoch 41/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3446 - accuracy: 0.8594
Epoch 42/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3437 - accuracy: 0.8622
Epoch 43/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8610
Epoch 44/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3423 - accuracy: 0.8616
Epoch 45/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3419 - accuracy: 0.8615
Epoch 46/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3411 - accuracy: 0.8625
Epoch 47/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.8619
Epoch 48/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3397 - accuracy: 0.8615
Epoch 49/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3395 - accuracy: 0.8631
Epoch 50/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3392 - accuracy: 0.8621

In [53]:
y_pred=model.predict(X_test_tf)

63/63 [==============================] - 0s 3ms/step

In [54]:
y_pred

array([[0.25196376],
       [0.34272528],
       [0.16666251],
       ...,
       [0.09690193],
       [0.12433141],
       [0.19714163]], dtype=float32)

In [58]:
y_pred=y_pred.argmax(axis=-1)

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7975